import Head from "next/head"

export default function SiteHead() {
    return (
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="robots" content="noindex"></meta>
            <meta name="googlebot" content="noindex"></meta>

            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}
